# Generated by Django 3.0.8 on 2020-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=10, verbose_name='Координата X')),
                ('y', models.CharField(max_length=10, verbose_name='Координата Y')),
                ('r', models.CharField(max_length=10, verbose_name='Радиус окружности')),
            ],
        ),
    ]
